CREATE DATABASE Questao02DCL

go

Use Questao02DCL

go

CREATE TABLE IF NOT EXISTS PRODUTOS
( 
	  IDPRODUTO smallint identity(1,1)
	, NOME_PROD varchar(50)  null
	, PRC_PROD  decimal(10,2) not null
	, constraint pkProdutos primary key (IDPRODUTO)
)

go

CREATE TABLE IF NOT EXISTS CORES
( 
	  NOME_COR  varchar(50) not null
	, PRC_COR   decimal(10,2) not null
	, IDPRODUTO smallint null 
	, constraint fkCores_IDPRODUTO foreign key (IDPRODUTO) references PRODUTOS(IDPRODUTO)
)

go

INSERT INTO PRODUTOS VALUES('Monitor LCD Samsung 740N', 750.00)
INSERT INTO PRODUTOS VALUES('Mouse Microsoft', 40.00)
INSERT INTO PRODUTOS VALUES('Notebook Sony Vaio', 11320.34)
INSERT INTO PRODUTOS VALUES(null, 392.99)
INSERT INTO CORES VALUES('Preto', 5.00, 1)
INSERT INTO CORES VALUES('Azul', 10.00, 1)
INSERT INTO CORES VALUES('Amarelo', 20.00, 2)
INSERT INTO CORES VALUES('Chumbo', 3.00, 4)

SELECT * FROM PRODUTOS
SELECT * FROM CORES

SELECT p.NOME_PROD
	,COALESCE(p.PRC_PROD + c.PRC_COR, p.PRC_PROD) AS PRECO_PRODUTO
	,convert( decimal(10,2), COALESCE(p.PRC_PROD + c.PRC_COR, p.PRC_PROD) + (COALESCE(p.PRC_PROD + c.PRC_COR, p.PRC_PROD) * 0.1)) AS PRECO_ACRESCIMO_10
	,convert( decimal(10,2), COALESCE(p.PRC_PROD + c.PRC_COR, p.PRC_PROD) - (COALESCE(p.PRC_PROD + c.PRC_COR, p.PRC_PROD) * 0.1)) AS PRECO_DESCONTO_10
	,c.NOME_COR
FROM PRODUTOS AS p LEFT JOIN CORES AS c ON c.IDPRODUTO = p.IDPRODUTO
WHERE p.NOME_PROD IS NOT NULL
ORDER BY p.PRC_PROD ASC
